name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yaml'
      - '**package.xml'
      - 'upstream.repos'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile
  upstream:
    strategy:
      matrix:
        ros_distro: [humble, rolling]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          target: upstream
          build-args: ROS_DISTRO=${{ matrix.ros_distro }}
          tags: ghcr.io/griswaldbrooks/development-container:upstream-${{ matrix.ros_distro }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
